"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.boardRoutes = void 0;
const express_1 = require("express");
const validators_helper_1 = require("../utils/helpers/validators.helper");
const board_controller_1 = require("../controllers/board.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const workspace_dto_1 = require("../dto/workspace.dto");
const exception_middleware_1 = require("../middlewares/exception.middleware");
exports.boardRoutes = (0, express_1.Router)();
const boardController = new board_controller_1.BoardController();
exports.boardRoutes.use(auth_middleware_1.protect);
exports.boardRoutes.post("/", (0, validators_helper_1.validator)({ dto: new workspace_dto_1.CreateBoardDto() }), (0, exception_middleware_1.exceptionEscalator)(boardController.create));
exports.boardRoutes.get("/", (0, exception_middleware_1.exceptionEscalator)(boardController.list));
exports.boardRoutes.get("/search", (0, exception_middleware_1.exceptionEscalator)(boardController.search));
exports.boardRoutes.get("/:boardId", (0, exception_middleware_1.exceptionEscalator)(boardController.get));
exports.boardRoutes.patch("/:boardId", (0, exception_middleware_1.exceptionEscalator)(boardController.update));
exports.boardRoutes.delete("/:boardId", (0, exception_middleware_1.exceptionEscalator)(boardController.delete));
